import dotenv from "dotenv";
import mongoose from "mongoose";
import Product from "./models/Product.js";

dotenv.config();

const products = [
  // ================================
  // PROTECTIVE EQUIPMENT
  // ================================

  {
    partNumber: "KGV1",
    name: "Karate Gloves S/M/L (Red+Blue Pair)",
    category: "Karate Equipment",
    unit: "Pair",
    sizes: ["S", "M", "L"],
    colours: ["Red", "Blue"],
    price: 740,
    singlePiecePrice: 370,
  },
  {
    partNumber: "KHG1",
    name: "Headguard S/M/L (Red/Blue)",
    category: "Protective Equipment",
    unit: "Piece",
    sizes: ["S", "M", "L"],
    colours: ["Red", "Blue"],
    price: 1100,
    singlePiecePrice: 1100,
  },
  {
    partNumber: "KSG1",
    name: "Shinguard S/M/L (Red/Blue)",
    category: "Protective Equipment",
    unit: "Pair",
    sizes: ["S", "M", "L"],
    colours: ["Red", "Blue"],
    price: 1320,
    singlePiecePrice: 660,
  },
  {
    partNumber: "KCG1",
    name: "Chestguard S/M/L",
    category: "Protective Equipment",
    unit: "Piece",
    sizes: ["S", "M", "L"],
    colours: [],
    price: 675,
    singlePiecePrice: 675,
  },
  {
    partNumber: "KTB1",
    name: "Kit Bag",
    category: "Bags",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 685,
    singlePiecePrice: 685,
  },
  {
    partNumber: "KMG1",
    name: "Mouth Guard",
    category: "Protective Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 50,
    singlePiecePrice: 50,
  },

  // ================================
  // BELTS
  // ================================

  {
    partNumber: "KBL1",
    name: "KIO Approved Red & Blue Belt",
    category: "Belt",
    unit: "Piece",
    sizes: [],
    colours: ["Red", "Blue"],
    price: 700,
    singlePiecePrice: 700,
  },
  {
    partNumber: "KCB1",
    name: "Colour Belt",
    category: "Belt",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 50,
    singlePiecePrice: 50,
  },
  {
    partNumber: "KBB1",
    name: "Black Belt M/L/XL/2XL/3XL",
    category: "Belt",
    unit: "Piece",
    sizes: ["M", "L", "XL", "2XL", "3XL"],
    colours: ["Black"],
    price: 370,
    singlePiecePrice: 370,
  },
  {
    partNumber: "KBE1",
    name: "Black Belt with Embroidery",
    category: "Belt",
    unit: "Piece",
    sizes: [],
    colours: ["Black"],
    price: 640,
    singlePiecePrice: 640,
  },

  // ================================
  // TRAINING EQUIPMENT
  // ================================

  {
    partNumber: "KTP1",
    name: "Target Pad Single",
    category: "Training Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 330,
    singlePiecePrice: 330,
  },
  {
    partNumber: "KTP2",
    name: "Target Pad Double",
    category: "Training Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 400,
    singlePiecePrice: 400,
  },
  {
    partNumber: "KSF1",
    name: "Kicking Shield Full",
    category: "Training Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 1600,
    singlePiecePrice: 1600,
  },
  {
    partNumber: "KSH1",
    name: "Kicking Shield Half",
    category: "Training Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 870,
    singlePiecePrice: 870,
  },
  {
    partNumber: "KTH1",
    name: "Thai Pad",
    category: "Training Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 1150,
    singlePiecePrice: 1150,
  },
  {
    partNumber: "KFP1",
    name: "Focus Pad No.1",
    category: "Training Equipment",
    unit: "Pair",
    sizes: [],
    colours: [],
    price: 950,
    singlePiecePrice: 475,
  },
  {
    partNumber: "KFR1",
    name: "Focus Pad Regular",
    category: "Training Equipment",
    unit: "Pair",
    sizes: [],
    colours: [],
    price: 750,
    singlePiecePrice: 375,
  },

  // ================================
  // KITS
  // ================================

  {
    partNumber: "KPK1",
    name: "Gokaido Professional Kit",
    category: "Kit",
    unit: "Set",
    sizes: [],
    colours: [],
    price: 6300,
  },
  {
    partNumber: "KGK1",
    name: "Gokaido KIO Approved Kit",
    category: "Kit",
    unit: "Set",
    sizes: [],
    colours: [],
    price: 4670,
  },

  // ================================
  // MARTIAL ARTS WEAPONS
  // ================================

  {
    partNumber: "KTF1",
    name: "Tonfa",
    category: "Martial Arts Equipment",
    unit: "Pair",
    sizes: [],
    colours: [],
    price: 1100,
    singlePiecePrice: 550,
  },
  {
    partNumber: "KNW1",
    name: "Nanchak Wooden",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 140,
    singlePiecePrice: 140,
  },
  {
    partNumber: "KNF1",
    name: "Nanchak Wood with Foam",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 140,
    singlePiecePrice: 140,
  },
  {
    partNumber: "KNS1",
    name: "Nanchak Steel",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 180,
    singlePiecePrice: 180,
  },
  {
    partNumber: "KNSF1",
    name: "Nanchak Steel Foam",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 120,
    singlePiecePrice: 120,
  },
  {
    partNumber: "KNP1",
    name: "Pencil Nanchak",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 80,
    singlePiecePrice: 80,
  },

  // ================================
  // PUNCHING BAGS
  // ================================

  {
    partNumber: "KCP2",
    name: "Canvas Punching Bag 2 Feet (Without Fill)",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["2 Feet"],
    colours: [],
    price: 380,
    singlePiecePrice: 380,
  },
  {
    partNumber: "KCP3",
    name: "Canvas Punching Bag 3 Feet (Without Fill)",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["3 Feet"],
    colours: [],
    price: 420,
    singlePiecePrice: 420,
  },
  {
    partNumber: "KCP4",
    name: "Canvas Punching Bag 4 Feet (Without Fill)",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["4 Feet"],
    colours: [],
    price: 460,
    singlePiecePrice: 460,
  },
  {
    partNumber: "KCP5",
    name: "Canvas Punching Bag 5 Feet (Without Fill)",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["5 Feet"],
    colours: [],
    price: 530,
    singlePiecePrice: 530,
  },

  {
    partNumber: "KPR3",
    name: "Punching Bag Rexine Filled 3 Feet",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["3 Feet"],
    colours: [],
    price: 3500,
    singlePiecePrice: 3500,
  },
  {
    partNumber: "KPR4",
    name: "Punching Bag Rexine Filled 4 Feet",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["4 Feet"],
    colours: [],
    price: 3950,
    singlePiecePrice: 3950,
  },
  {
    partNumber: "KPR5",
    name: "Punching Bag Rexine Filled 5 Feet",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["5 Feet"],
    colours: [],
    price: 5300,
    singlePiecePrice: 5300,
  },
  {
    partNumber: "KPR6",
    name: "Punching Bag Rexine Filled 6 Feet",
    category: "Punching Bag",
    unit: "Piece",
    sizes: ["6 Feet"],
    colours: [],
    price: 6100,
    singlePiecePrice: 6100,
  },

  // ================================
  // LATI / BAGS
  // ================================

  {
    partNumber: "KLT4",
    name: "Lati 4 Feet",
    category: "Training Equipment",
    unit: "Piece",
    sizes: ["4 Feet"],
    colours: [],
    price: 160,
    singlePiecePrice: 160,
  },
  {
    partNumber: "KLT5",
    name: "Lati 5 Feet",
    category: "Training Equipment",
    unit: "Piece",
    sizes: ["5 Feet"],
    colours: [],
    price: 190,
    singlePiecePrice: 190,
  },
  {
    partNumber: "KLT6",
    name: "Lati 6 Feet",
    category: "Training Equipment",
    unit: "Piece",
    sizes: ["6 Feet"],
    colours: [],
    price: 190,
    singlePiecePrice: 190,
  },
  {
    partNumber: "KLB1",
    name: "Leather Bag",
    category: "Bags",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 2200,
    singlePiecePrice: 2200,
  },
  {
    partNumber: "KIN1",
    name: "Import Nanchak with Rope",
    category: "Martial Arts Equipment",
    unit: "Piece",
    sizes: [],
    colours: [],
    price: 165,
    singlePiecePrice: 165,
  },

  // ================================
  // BOXING GLOVES
  // ================================

  {
    partNumber: "KBG10",
    name: "Boxing Gloves Multiprint 10oz",
    category: "Boxing Equipment",
    unit: "Pair",
    sizes: ["10oz"],
    colours: [],
    price: 940,
    singlePiecePrice: 470,
  },
  {
    partNumber: "KBG12",
    name: "Boxing Gloves Multiprint 12oz",
    category: "Boxing Equipment",
    unit: "Pair",
    sizes: ["12oz"],
    colours: [],
    price: 955,
    singlePiecePrice: 477.5,
  },
  {
    partNumber: "KBG14",
    name: "Boxing Gloves Multiprint 14oz",
    category: "Boxing Equipment",
    unit: "Pair",
    sizes: ["14oz"],
    colours: [],
    price: 970,
    singlePiecePrice: 485,
  },
  {
    partNumber: "KBG16",
    name: "Boxing Gloves Multiprint 16oz",
    category: "Boxing Equipment",
    unit: "Pair",
    sizes: ["16oz"],
    colours: [],
    price: 990,
    singlePiecePrice: 495,
  },

  // ================================
  // STUDENT PRACTICE DRESS
  // ================================

  {
    partNumber: "UPP1326",
    name: "Student Practice Dress Gokaido Premium Quality 13/26",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["13/26"],
    colours: [],
    price: 395,
  },
  {
    partNumber: "UPP1428",
    name: "Student Practice Dress Gokaido Premium Quality 14/28",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["14/28"],
    colours: [],
    price: 410,
  },
  {
    partNumber: "UPP1530",
    name: "Student Practice Dress Gokaido Premium Quality 15/30",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["15/30"],
    colours: [],
    price: 425,
  },
  {
    partNumber: "UPP1632",
    name: "Student Practice Dress Gokaido Premium Quality 16/32",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["16/32"],
    colours: [],
    price: 435,
  },
  {
    partNumber: "UPP1734",
    name: "Student Practice Dress Gokaido Premium Quality 17/34",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["17/34"],
    colours: [],
    price: 450,
  },
  {
    partNumber: "UPP1836",
    name: "Student Practice Dress Gokaido Premium Quality 18/36",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["18/36"],
    colours: [],
    price: 460,
  },
  {
    partNumber: "UPP1937",
    name: "Student Practice Dress Gokaido Premium Quality 19/37",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["19/37"],
    colours: [],
    price: 485,
  },
  {
    partNumber: "UPP2038",
    name: "Student Practice Dress Gokaido Premium Quality 20/38",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["20/38"],
    colours: [],
    price: 515,
  },
  {
    partNumber: "UPP2139",
    name: "Student Practice Dress Gokaido Premium Quality 21/39",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["21/39"],
    colours: [],
    price: 525,
  },
  {
    partNumber: "UPP2240",
    name: "Student Practice Dress Gokaido Premium Quality 22/40",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["22/40"],
    colours: [],
    price: 540,
  },
  {
    partNumber: "UPP2341",
    name: "Student Practice Dress Gokaido Premium Quality 23/41",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["23/41"],
    colours: [],
    price: 550,
  },
  {
    partNumber: "UPP2442",
    name: "Student Practice Dress Gokaido Premium Quality 24/42",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["24/42"],
    colours: [],
    price: 570,
  },
  {
    partNumber: "UPP2543",
    name: "Student Practice Dress Gokaido Premium Quality 25/43",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["25/43"],
    colours: [],
    price: 575,
  },
  {
    partNumber: "UPP2644",
    name: "Student Practice Dress Gokaido Premium Quality 26/44",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["26/44"],
    colours: [],
    price: 590,
  },
  {
    partNumber: "UPY1",
    name: "Student Practice Dress Yuso Quality (All Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["All Size"],
    colours: [],
    price: 490,
  },

  // ================================
  // CLASSIC QUALITY DRESS
  // ================================

  {
    partNumber: "UPC1326",
    name: "Student Practice Dress Classic Quality 13/26",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["13/26"],
    colours: [],
    price: 410,
  },
  {
    partNumber: "UPC1428",
    name: "Student Practice Dress Classic Quality 14/28",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["14/28"],
    colours: [],
    price: 410,
  },
  {
    partNumber: "UPC1530",
    name: "Student Practice Dress Classic Quality 15/30",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["15/30"],
    colours: [],
    price: 445,
  },
  {
    partNumber: "UPC1632",
    name: "Student Practice Dress Classic Quality 16/32",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["16/32"],
    colours: [],
    price: 445,
  },
  {
    partNumber: "UPC1734",
    name: "Student Practice Dress Classic Quality 17/34",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["17/34"],
    colours: [],
    price: 445,
  },
  {
    partNumber: "UPC1836",
    name: "Student Practice Dress Classic Quality 18/36",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["18/36"],
    colours: [],
    price: 475,
  },
  {
    partNumber: "UPC2038",
    name: "Student Practice Dress Classic Quality 20/38",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["20/38"],
    colours: [],
    price: 475,
  },
  {
    partNumber: "UPC2240",
    name: "Student Practice Dress Classic Quality 22/40",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["22/40"],
    colours: [],
    price: 495,
  },
  {
    partNumber: "UPC2442",
    name: "Student Practice Dress Classic Quality 24/42",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["24/42"],
    colours: [],
    price: 495,
  },
  {
    partNumber: "UPC2644",
    name: "Student Practice Dress Classic Quality 26/44",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["26/44"],
    colours: [],
    price: 505,
  },

  // ================================
  // EXPORT QUALITY DRESS
  // ================================

  {
    partNumber: "UPE1224S",
    name: "Student Practice Dress Gokaido Export Quality 12/24 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["12/24"],
    colours: [],
    price: 495,
  },
  {
    partNumber: "UPE1224P",
    name: "Student Practice Dress Gokaido Export Quality 12/24 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["12/24"],
    colours: [],
    price: 515,
  },
  {
    partNumber: "UPE1326S",
    name: "Student Practice Dress Gokaido Export Quality 13/26 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["13/26"],
    colours: [],
    price: 515,
  },
  {
    partNumber: "UPE1326P",
    name: "Student Practice Dress Gokaido Export Quality 13/26 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["13/26"],
    colours: [],
    price: 535,
  },
  {
    partNumber: "UPE1428S",
    name: "Student Practice Dress Gokaido Export Quality 14/28 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["14/28"],
    colours: [],
    price: 535,
  },
  {
    partNumber: "UPE1428P",
    name: "Student Practice Dress Gokaido Export Quality 14/28 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["14/28"],
    colours: [],
    price: 555,
  },
  {
    partNumber: "UPE1530S",
    name: "Student Practice Dress Gokaido Export Quality 15/30 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["15/30"],
    colours: [],
    price: 555,
  },
  {
    partNumber: "UPE1530P",
    name: "Student Practice Dress Gokaido Export Quality 15/30 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["15/30"],
    colours: [],
    price: 575,
  },
  {
    partNumber: "UPE1632S",
    name: "Student Practice Dress Gokaido Export Quality 16/32 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["16/32"],
    colours: [],
    price: 575,
  },
  {
    partNumber: "UPE1632P",
    name: "Student Practice Dress Gokaido Export Quality 16/32 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["16/32"],
    colours: [],
    price: 595,
  },
  {
    partNumber: "UPE1734S",
    name: "Student Practice Dress Gokaido Export Quality 17/34 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["17/34"],
    colours: [],
    price: 595,
  },
  {
    partNumber: "UPE1734P",
    name: "Student Practice Dress Gokaido Export Quality 17/34 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["17/34"],
    colours: [],
    price: 615,
  },
  {
    partNumber: "UPE1836S",
    name: "Student Practice Dress Gokaido Export Quality 18/36 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["18/36"],
    colours: [],
    price: 625,
  },
  {
    partNumber: "UPE1836P",
    name: "Student Practice Dress Gokaido Export Quality 18/36 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["18/36"],
    colours: [],
    price: 645,
  },
  {
    partNumber: "UPE1937S",
    name: "Student Practice Dress Gokaido Export Quality 19/37 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["19/37"],
    colours: [],
    price: 655,
  },
  {
    partNumber: "UPE1937P",
    name: "Student Practice Dress Gokaido Export Quality 19/37 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["19/37"],
    colours: [],
    price: 675,
  },
  {
    partNumber: "UPE2038S",
    name: "Student Practice Dress Gokaido Export Quality 20/38 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["20/38"],
    colours: [],
    price: 690,
  },
  {
    partNumber: "UPE2038P",
    name: "Student Practice Dress Gokaido Export Quality 20/38 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["20/38"],
    colours: [],
    price: 720,
  },
  {
    partNumber: "UPE2139S",
    name: "Student Practice Dress Gokaido Export Quality 21/39 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["21/39"],
    colours: [],
    price: 710,
  },
  {
    partNumber: "UPE2139P",
    name: "Student Practice Dress Gokaido Export Quality 21/39 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["21/39"],
    colours: [],
    price: 740,
  },
  {
    partNumber: "UPE2240S",
    name: "Student Practice Dress Gokaido Export Quality 22/40 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["22/40"],
    colours: [],
    price: 745,
  },
  {
    partNumber: "UPE2240P",
    name: "Student Practice Dress Gokaido Export Quality 22/40 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["22/40"],
    colours: [],
    price: 775,
  },
  {
    partNumber: "UPE2341S",
    name: "Student Practice Dress Gokaido Export Quality 23/41 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["23/41"],
    colours: [],
    price: 770,
  },
  {
    partNumber: "UPE2341P",
    name: "Student Practice Dress Gokaido Export Quality 23/41 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["23/41"],
    colours: [],
    price: 800,
  },
  {
    partNumber: "UPE2442S",
    name: "Student Practice Dress Gokaido Export Quality 24/42 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["24/42"],
    colours: [],
    price: 790,
  },
  {
    partNumber: "UPE2442P",
    name: "Student Practice Dress Gokaido Export Quality 24/42 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["24/42"],
    colours: [],
    price: 830,
  },
  {
    partNumber: "UPE2543S",
    name: "Student Practice Dress Gokaido Export Quality 25/43 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["25/43"],
    colours: [],
    price: 810,
  },
  {
    partNumber: "UPE2543P",
    name: "Student Practice Dress Gokaido Export Quality 25/43 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["25/43"],
    colours: [],
    price: 850,
  },
  {
    partNumber: "UPE2644S",
    name: "Student Practice Dress Gokaido Export Quality 26/44 (Slim Fit)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["26/44"],
    colours: [],
    price: 830,
  },
  {
    partNumber: "UPE2644P",
    name: "Student Practice Dress Gokaido Export Quality 26/44 (SP Size)",
    category: "Karate Dress",
    unit: "Set",
    sizes: ["26/44"],
    colours: [],
    price: 870,
  },

  // ================================
  // THUNDER CANVAS / KATA DRESS
  // ================================

  {
    partNumber: "UTC1530T",
    name: "Thunder Canvas/Kata Dress 15/30 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["15/30"],
    colours: ["Thunder"],
    price: 2070,
    singlePiecePrice: 2070,
  },
  {
    partNumber: "UTC1530P",
    name: "Thunder Canvas/Kata Dress 15/30 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["15/30"],
    colours: ["Paper"],
    price: 1785,
    singlePiecePrice: 1785,
  },
  {
    partNumber: "UTC1632T",
    name: "Thunder Canvas/Kata Dress 16/32 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["16/32"],
    colours: ["Thunder"],
    price: 2130,
    singlePiecePrice: 2130,
  },
  {
    partNumber: "UTC1632P",
    name: "Thunder Canvas/Kata Dress 16/32 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["16/32"],
    colours: ["Paper"],
    price: 1850,
    singlePiecePrice: 1850,
  },
  {
    partNumber: "UTC1734T",
    name: "Thunder Canvas/Kata Dress 17/34 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["17/34"],
    colours: ["Thunder"],
    price: 2195,
    singlePiecePrice: 2195,
  },
  {
    partNumber: "UTC1734P",
    name: "Thunder Canvas/Kata Dress 17/34 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["17/34"],
    colours: ["Paper"],
    price: 1910,
    singlePiecePrice: 1910,
  },
  {
    partNumber: "UTC1836T",
    name: "Thunder Canvas/Kata Dress 18/36 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["18/36"],
    colours: ["Thunder"],
    price: 2250,
    singlePiecePrice: 2250,
  },
  {
    partNumber: "UTC1836P",
    name: "Thunder Canvas/Kata Dress 18/36 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["18/36"],
    colours: ["Paper"],
    price: 1980,
    singlePiecePrice: 1980,
  },
  {
    partNumber: "UTC1937T",
    name: "Thunder Canvas/Kata Dress 19/37 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["19/37"],
    colours: ["Thunder"],
    price: 2320,
    singlePiecePrice: 2320,
  },
  {
    partNumber: "UTC1937P",
    name: "Thunder Canvas/Kata Dress 19/37 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["19/37"],
    colours: ["Paper"],
    price: 2035,
    singlePiecePrice: 2035,
  },
  {
    partNumber: "UTC2038T",
    name: "Thunder Canvas/Kata Dress 20/38 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["20/38"],
    colours: ["Thunder"],
    price: 2375,
    singlePiecePrice: 2375,
  },
  {
    partNumber: "UTC2038P",
    name: "Thunder Canvas/Kata Dress 20/38 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["20/38"],
    colours: ["Paper"],
    price: 2095,
    singlePiecePrice: 2095,
  },
  {
    partNumber: "UTC2139T",
    name: "Thunder Canvas/Kata Dress 21/39 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["21/39"],
    colours: ["Thunder"],
    price: 2430,
    singlePiecePrice: 2430,
  },
  {
    partNumber: "UTC2139P",
    name: "Thunder Canvas/Kata Dress 21/39 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["21/39"],
    colours: ["Paper"],
    price: 2160,
    singlePiecePrice: 2160,
  },
  {
    partNumber: "UTC2240T",
    name: "Thunder Canvas/Kata Dress 22/40 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["22/40"],
    colours: ["Thunder"],
    price: 2495,
    singlePiecePrice: 2495,
  },
  {
    partNumber: "UTC2240P",
    name: "Thunder Canvas/Kata Dress 22/40 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["22/40"],
    colours: ["Paper"],
    price: 2220,
    singlePiecePrice: 2220,
  },
  {
    partNumber: "UTC2341T",
    name: "Thunder Canvas/Kata Dress 23/41 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["23/41"],
    colours: ["Thunder"],
    price: 2550,
    singlePiecePrice: 2550,
  },
  {
    partNumber: "UTC2341P",
    name: "Thunder Canvas/Kata Dress 23/41 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["23/41"],
    colours: ["Paper"],
    price: 2285,
    singlePiecePrice: 2285,
  },
  {
    partNumber: "UTC2442T",
    name: "Thunder Canvas/Kata Dress 24/42 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["24/42"],
    colours: ["Thunder"],
    price: 2620,
    singlePiecePrice: 2620,
  },
  {
    partNumber: "UTC2442P",
    name: "Thunder Canvas/Kata Dress 24/42 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["24/42"],
    colours: ["Paper"],
    price: 2350,
    singlePiecePrice: 2350,
  },
  {
    partNumber: "UTC2543T",
    name: "Thunder Canvas/Kata Dress 25/43 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["25/43"],
    colours: ["Thunder"],
    price: 2680,
    singlePiecePrice: 2680,
  },
  {
    partNumber: "UTC2543P",
    name: "Thunder Canvas/Kata Dress 25/43 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["25/43"],
    colours: ["Paper"],
    price: 2410,
    singlePiecePrice: 2410,
  },
  {
    partNumber: "UTC2644T",
    name: "Thunder Canvas/Kata Dress 26/44 (Thunder)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["26/44"],
    colours: ["Thunder"],
    price: 2830,
    singlePiecePrice: 2830,
  },
  {
    partNumber: "UTC2644P",
    name: "Thunder Canvas/Kata Dress 26/44 (Paper)",
    category: "Karate Dress",
    unit: "Piece",
    sizes: ["26/44"],
    colours: ["Paper"],
    price: 2490,
    singlePiecePrice: 2490,
  },

  // ================================
  // KUMITE / FIGHTING DRESS
  // ================================

  {
    partNumber: "UKD16322",
    name: "Kumite/Fighting Dress 16/32 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["16/32"],
    colours: [],
    price: 2990,
  },
  {
    partNumber: "UKD16321",
    name: "Kumite/Fighting Dress 16/32 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["16/32"],
    colours: [],
    price: 1770,
    singlePiecePrice: 1770,
  },
  {
    partNumber: "UKD17342",
    name: "Kumite/Fighting Dress 17/34 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["17/34"],
    colours: [],
    price: 2990,
  },
  {
    partNumber: "UKD17341",
    name: "Kumite/Fighting Dress 17/34 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["17/34"],
    colours: [],
    price: 1770,
    singlePiecePrice: 1770,
  },
  {
    partNumber: "UKD18362",
    name: "Kumite/Fighting Dress 18/36 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["18/36"],
    colours: [],
    price: 2990,
  },
  {
    partNumber: "UKD18361",
    name: "Kumite/Fighting Dress 18/36 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["18/36"],
    colours: [],
    price: 1770,
    singlePiecePrice: 1770,
  },
  {
    partNumber: "UKD19372",
    name: "Kumite/Fighting Dress 19/37 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["19/37"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD19371",
    name: "Kumite/Fighting Dress 19/37 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["19/37"],
    colours: [],
    price: 1890,
    singlePiecePrice: 1890,
  },
  {
    partNumber: "UKD20382",
    name: "Kumite/Fighting Dress 20/38 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["20/38"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD20381",
    name: "Kumite/Fighting Dress 20/38 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["20/38"],
    colours: [],
    price: 1890,
    singlePiecePrice: 1890,
  },
  {
    partNumber: "UKD21392",
    name: "Kumite/Fighting Dress 21/39 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["21/39"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD21391",
    name: "Kumite/Fighting Dress 21/39 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["21/39"],
    colours: [],
    price: 1890,
    singlePiecePrice: 1890,
  },
  {
    partNumber: "UKD22402",
    name: "Kumite/Fighting Dress 22/40 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["22/40"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD22401",
    name: "Kumite/Fighting Dress 22/40 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["22/40"],
    colours: [],
    price: 1890,
    singlePiecePrice: 1890,
  },
  {
    partNumber: "UKD23412",
    name: "Kumite/Fighting Dress 23/41 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["23/41"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD23411",
    name: "Kumite/Fighting Dress 23/41 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["23/41"],
    colours: [],
    price: 1890,
    singlePiecePrice: 1890,
  },
  {
    partNumber: "UKD24422",
    name: "Kumite/Fighting Dress 24/42 (2 Top Set)",
    category: "Kumite Dress",
    unit: "Set",
    sizes: ["24/42"],
    colours: [],
    price: 3100,
  },
  {
    partNumber: "UKD24421",
    name: "Kumite/Fighting Dress 24/42 (1 Top)",
    category: "Kumite Dress",
    unit: "Piece",
    sizes: ["24/42"],
    colours: [],
    price: 1990,
    singlePiecePrice: 1990,
  },
];

// ================================
// SEED PRODUCTS
// ================================

const seedProducts = async () => {
  try {
    if (!process.env.MONGO_URI) {
      throw new Error("MONGO_URI is not defined in .env");
    }

    await mongoose.connect(process.env.MONGO_URI);

    console.log("Connected to MongoDB");

    let added = 0;
    let updated = 0;

    for (const product of products) {
      const existingProduct = await Product.findOne({
        partNumber: product.partNumber,
      });

      if (existingProduct) {
        await Product.findOneAndUpdate(
          { partNumber: product.partNumber },
          product,
          {
            new: true,
            runValidators: true,
          }
        );

        updated++;
      } else {
        await Product.create(product);
        added++;
      }
    }

    console.log("-----------------------------------");
    console.log("Products seeded successfully");
    console.log(`Products added: ${added}`);
    console.log(`Products updated: ${updated}`);
    console.log(`Total products processed: ${products.length}`);
    console.log("-----------------------------------");

    await mongoose.disconnect();

    console.log("MongoDB connection closed");

    process.exit(0);
  } catch (error) {
    console.error("Product seed error:", error.message);

    try {
      await mongoose.disconnect();
    } catch (disconnectError) {
      console.error(
        "MongoDB disconnect error:",
        disconnectError.message
      );
    }

    process.exit(1);
  }
};

seedProducts();